### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in krumo::_object() (line 1156 ../class.krumo.php).

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/devel#101]
This issue is similar to https://github.com/backdrop-contrib/devel/issues/44, however is about the different line:

```
Warning: count(): Parameter must be an array or an object that implements Countable in krumo::_object() (line 1156 of /home/in/public_html/modules/devel/lib/krumo/class.krumo.php).
```

Replaced the line with:

```
<div class="krumo-element<?php echo !empty($data) ? ' krumo-expand' : '';?>">
```
 and it works for my use case. However, since the file has number of other occurrences of `count()`, they all should be properly re-worked for the newer PHP versions.

**Comment by kktsvetkov** [comment]
Can you try upgrading Krumo, I think this is fixed in https://github.com/kktsvetkov/krumo/releases/tag/0.4.1

**Comment by jenlampton** [comment]
I replaced the old krumo lib with version 0.4.1 and I still have the error:
```
Warning: count(): Parameter must be an array or an object that implements Countable in krumo::_object() (line 1156 of backdrop/modules/contrib/devel/lib/krumo/class.krumo.php).
```

edit: apologies, this is not the version 0.4.1. Will try again.

**Comment by jenlampton** [comment]
The devel module is using version 2.0.1a, but [the krumo fix](https://github.com/kktsvetkov/krumo/commit/93e1a89626ffd1b587b1415865fd7c8f12c9335f) was added to a much more recent version. I tried applying the patch to 2.0.1a but, unsurprisingly, it failed :) 

We can add our own fix directly to the older version of the krumo library as follows:
```php
<?php
  /**
  * Render a dump for an object
  *
  * @param mixed $data
  * @param string $name
  * @access private
  * @static
  */
  Private Static Function _object(&$data, $name) {
    $count = 1;
    if (is_array($data) || $data instanceof Countable) {
      $count = count($data);
    }
?>
<li class="krumo-child">

  <div class="krumo-element<?php echo $count > 0 ? ' krumo-expand' : '';?>">
```

...but it would probably be better to figure out how to make a newer version work.

**Comment by jenlampton** [comment]
PR here could use a review.

**Comment by ghost** [comment]
PR works for me. @quicksketch or @backdrop-contrib/bug-squad care to merge & release new version?

**Comment by jenlampton** [comment]
I've merged the PR, but the bug squad isn't authorized to make a new release.

**Comment by bradbulger** [comment]
The old behavior when you called count() on a non-countable variable was 0 for NULL and 1 for anything else. Should this be emulating that?

**Comment by kktsvetkov** [comment]
@jenlampton I think that code snippet with `Countable` might be from an old krumo fork and not from my project. What I do instead of the counting of the properties is to use a flag called `$has_properties`

```php 
/**
* Render a dump for an object
*
* @param mixed $data
* @param string $name
*/
private static function _object(&$data, $name)
{
	$has_properties = !empty(get_object_vars($data));
	?>
	<li class="krumo-child">
		<div <?php if ($has_properties) {?> onClick="krumo.toggle(this);"<?php } ?>
...
```

https://github.com/kktsvetkov/krumo/blob/master/class.krumo.php#L1139

**Comment by jenlampton** [comment]
Thanks @kktsvetkov!

I had mentioned [above](https://github.com/backdrop-contrib/devel/issues/101#issuecomment-668924708) that we are, in fact, using a very old version of Krumo that still contains the `count()` calls. I also linked to the commit where Krumo switched to using `$has_properties` instead. 

We certainly need to update! Hence, #102.
